version: v1.0
run:
  go: '1.24'
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - revive
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - unparam
    - bodyclose

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-same-issues: 0

output:
  format: colored-line-number

service:
  golangci-lint-version: 'v2.1.5'
