version: "2"
run:
  build-tags:
    - integration
  tests: true
linters:
  enable:
    - bodyclose
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G204
        - G304
    revive:
      rules:
        - name: package-comments
          disabled: false
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor/
      - tests/
      - testdata/
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor/
      - tests/
      - testdata/
      - third_party$
      - builtin$
      - examples$
