linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - revive
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - unparam
    - bodyclose

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
