# Build settings
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go
    binary: nsm

# Archives settings
archives:
  - format: tar.gz
    files:
      - nsm
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}"

# Docker settings
dockers:
  - image_templates:
      - "mdaashir/nsm:{{ .Version }}"
      - "mdaashir/nsm:latest"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile

# Release settings
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

# GitHub release settings
release:
  github:
    owner: mdaashir
    name: nsm
