# Build settings
builds:
  - os:
      - linux
      - darwin
      - windows
    arch:
      - amd64
    main: ./main.go
    binary: nsm

# Archives settings
archives:
  - format: tar.gz
    files:
      - nsm
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}"

# Docker settings
docker:
  images:
    - name: "mdaashir/nsm:{{ .Version }}"
    - name: "mdaashir/nsm:latest"
      use: buildx
      build_flag_templates:
        - "--platform=linux/amd64"
      dockerfile: Dockerfile

# Release settings
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

# GitHub release settings
release:
  github:
    owner: mdaashir
    name: nsm
