# Build settings
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go
    binary: nsm
    ldflags:
      - -s -w

# Archives settings
archives:
  - id: nsm
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# Docker settings
dockers:
  - image_templates:
      - "mdaashir/nsm:{{ .Version }}"
      - "mdaashir/nsm:latest"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum

# Release settings
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

# Customization
project_name: nsm

# GitHub release settings
release:
  github:
    owner: mdaashir
    name: nsm
  draft: false
  prerelease: auto

# Before build hooks
before:
  hooks:
    - go mod tidy

# Checksum settings
checksum:
  name_template: 'checksums.txt'
