# Build settings
builds:
  - os: [linux, darwin, windows]
    arch: amd64
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go
    binary: nsm

# Archives settings
archives:
  - format: tar.gz
    files:
      - nsm
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}.tar.gz"

# Docker settings (optional)
dockers:
  - image: nsm
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile

# Release settings
changelog:
  sort: asc
  filters:
    exclude:
      - "exclude-regex"

# GitHub release settings
release:
  github:
    owner: mdaashir
    name: nsm
